# Site settings
name: WFH Excuse Generator
version: 0.1.1
author: Max Quattromani
email: max@maxquattromani.com
description: ""
baseurl: "/WFH-generator"
url: "http://maxquattromani.com"
author: "Max Quattromani"
twitter_username: maxquattromani
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty
highlighter: true

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: false
google_analytics_id: UA-50387096-4
jquery_version: 1.9.0

footer: ""
